/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedTerminalRouteImport } from './routes/_authenticated/terminal'
import { Route as AuthenticatedBudgetRouteImport } from './routes/_authenticated/budget'
import { Route as AuthenticatedForgeRouteImport } from './routes/_authenticated/forge'
import { Route as ApiPublicCronMondayBoardRouteImport } from './routes/api/public/cron/monday-board'
import { Route as ApiPublicCronJobTickRouteImport } from './routes/api/public/cron/job-tick'
import { Route as ApiPublicCronDailyReportsRouteImport } from './routes/api/public/cron/daily-reports'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTerminalRoute = AuthenticatedTerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBudgetRoute = AuthenticatedBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedForgeRoute = AuthenticatedForgeRouteImport.update({
  id: '/forge',
  path: '/forge',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicCronMondayBoardRoute =
  ApiPublicCronMondayBoardRouteImport.update({
    id: '/api/public/cron/monday-board',
    path: '/api/public/cron/monday-board',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronJobTickRoute = ApiPublicCronJobTickRouteImport.update({
  id: '/api/public/cron/job-tick',
  path: '/api/public/cron/job-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronDailyReportsRoute =
  ApiPublicCronDailyReportsRouteImport.update({
    id: '/api/public/cron/daily-reports',
    path: '/api/public/cron/daily-reports',
    getParentRoute: () => rootRouteImport,
  } as any)

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedTerminalRoute: typeof AuthenticatedTerminalRoute
  AuthenticatedBudgetRoute: typeof AuthenticatedBudgetRoute
  AuthenticatedForgeRoute: typeof AuthenticatedForgeRoute
}
const authenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute,
  AuthenticatedChatRoute,
  AuthenticatedTerminalRoute,
  AuthenticatedBudgetRoute,
  AuthenticatedForgeRoute,
}
const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  authenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/chat': typeof AuthenticatedChatRoute
  '/terminal': typeof AuthenticatedTerminalRoute
  '/budget': typeof AuthenticatedBudgetRoute
  '/forge': typeof AuthenticatedForgeRoute
  '/api/public/cron/daily-reports': typeof ApiPublicCronDailyReportsRoute
  '/api/public/cron/job-tick': typeof ApiPublicCronJobTickRoute
  '/api/public/cron/monday-board': typeof ApiPublicCronMondayBoardRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/chat': typeof AuthenticatedChatRoute
  '/terminal': typeof AuthenticatedTerminalRoute
  '/budget': typeof AuthenticatedBudgetRoute
  '/forge': typeof AuthenticatedForgeRoute
  '/api/public/cron/daily-reports': typeof ApiPublicCronDailyReportsRoute
  '/api/public/cron/job-tick': typeof ApiPublicCronJobTickRoute
  '/api/public/cron/monday-board': typeof ApiPublicCronMondayBoardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/terminal': typeof AuthenticatedTerminalRoute
  '/_authenticated/budget': typeof AuthenticatedBudgetRoute
  '/_authenticated/forge': typeof AuthenticatedForgeRoute
  '/api/public/cron/daily-reports': typeof ApiPublicCronDailyReportsRoute
  '/api/public/cron/job-tick': typeof ApiPublicCronJobTickRoute
  '/api/public/cron/monday-board': typeof ApiPublicCronMondayBoardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/chat'
    | '/terminal'
    | '/budget'
    | '/forge'
    | '/api/public/cron/daily-reports'
    | '/api/public/cron/job-tick'
    | '/api/public/cron/monday-board'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/chat'
    | '/terminal'
    | '/budget'
    | '/forge'
    | '/api/public/cron/daily-reports'
    | '/api/public/cron/job-tick'
    | '/api/public/cron/monday-board'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/reset-password'
    | '/_authenticated'
    | '/_authenticated/'
    | '/_authenticated/chat'
    | '/_authenticated/terminal'
    | '/_authenticated/budget'
    | '/_authenticated/forge'
    | '/api/public/cron/daily-reports'
    | '/api/public/cron/job-tick'
    | '/api/public/cron/monday-board'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ApiPublicCronDailyReportsRoute: typeof ApiPublicCronDailyReportsRoute
  ApiPublicCronJobTickRoute: typeof ApiPublicCronJobTickRoute
  ApiPublicCronMondayBoardRoute: typeof ApiPublicCronMondayBoardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/terminal': {
      id: '/_authenticated/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof AuthenticatedTerminalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/budget': {
      id: '/_authenticated/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof AuthenticatedBudgetRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/forge': {
      id: '/_authenticated/forge'
      path: '/forge'
      fullPath: '/forge'
      preLoaderRoute: typeof AuthenticatedForgeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/cron/monday-board': {
      id: '/api/public/cron/monday-board'
      path: '/api/public/cron/monday-board'
      fullPath: '/api/public/cron/monday-board'
      preLoaderRoute: typeof ApiPublicCronMondayBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/job-tick': {
      id: '/api/public/cron/job-tick'
      path: '/api/public/cron/job-tick'
      fullPath: '/api/public/cron/job-tick'
      preLoaderRoute: typeof ApiPublicCronJobTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/daily-reports': {
      id: '/api/public/cron/daily-reports'
      path: '/api/public/cron/daily-reports'
      fullPath: '/api/public/cron/daily-reports'
      preLoaderRoute: typeof ApiPublicCronDailyReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  AuthRoute,
  ResetPasswordRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ApiPublicCronDailyReportsRoute,
  ApiPublicCronJobTickRoute,
  ApiPublicCronMondayBoardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
