/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTerminalRouteImport } from './routes/_authenticated/terminal'
import { Route as AuthenticatedOutboundRouteImport } from './routes/_authenticated/outbound'
import { Route as AuthenticatedForgeRouteImport } from './routes/_authenticated/forge'
import { Route as AuthenticatedCoworkRouteImport } from './routes/_authenticated/cowork'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedBudgetRouteImport } from './routes/_authenticated/budget'
import { Route as AuthenticatedAutomateRouteImport } from './routes/_authenticated/automate'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated/approvals'
import { Route as AuthenticatedAgentsModelsRouteImport } from './routes/_authenticated/agents-models'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedBudgetIndexRouteImport } from './routes/_authenticated/budget.index'
import { Route as ApiPublicGenerateLinkedinImageRouteImport } from './routes/api/public/generate-linkedin-image'
import { Route as AuthenticatedSettingsModelsRouteImport } from './routes/_authenticated/settings/models'
import { Route as AuthenticatedSettingsConnectionsRouteImport } from './routes/_authenticated/settings/connections'
import { Route as AuthenticatedOutboundArchiveRouteImport } from './routes/_authenticated/outbound.archive'
import { Route as AuthenticatedBudgetStatementsRouteImport } from './routes/_authenticated/budget.statements'
import { Route as AuthenticatedBudgetSensitivityRouteImport } from './routes/_authenticated/budget.sensitivity'
import { Route as AuthenticatedBudgetScenariosRouteImport } from './routes/_authenticated/budget.scenarios'
import { Route as AuthenticatedBudgetResultsRouteImport } from './routes/_authenticated/budget.results'
import { Route as AuthenticatedBudgetMonthlyRouteImport } from './routes/_authenticated/budget.monthly'
import { Route as AuthenticatedBudgetFinancingRouteImport } from './routes/_authenticated/budget.financing'
import { Route as AuthenticatedBudgetCompareRouteImport } from './routes/_authenticated/budget.compare'
import { Route as AuthenticatedBudgetChangelogRouteImport } from './routes/_authenticated/budget.changelog'
import { Route as AuthenticatedBudgetBoardRouteImport } from './routes/_authenticated/budget.board'
import { Route as AuthenticatedBudgetAssumptionsRouteImport } from './routes/_authenticated/budget.assumptions'
import { Route as ApiPublicCronWeeklyDraftsRouteImport } from './routes/api/public/cron/weekly-drafts'
import { Route as ApiPublicCronScheduledOutboundRouteImport } from './routes/api/public/cron/scheduled-outbound'
import { Route as ApiPublicCronScheduleTickRouteImport } from './routes/api/public/cron/schedule-tick'
import { Route as ApiPublicCronMondayBoardRouteImport } from './routes/api/public/cron/monday-board'
import { Route as ApiPublicCronLeadReplyTriageRouteImport } from './routes/api/public/cron/lead-reply-triage'
import { Route as ApiPublicCronJobTickRouteImport } from './routes/api/public/cron/job-tick'
import { Route as ApiPublicCronDailyReportsRouteImport } from './routes/api/public/cron/daily-reports'
import { Route as ApiPublicCronDailyReminderRouteImport } from './routes/api/public/cron/daily-reminder'
import { Route as ApiPublicCronApprovalSweeperRouteImport } from './routes/api/public/cron/approval-sweeper'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTerminalRoute = AuthenticatedTerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOutboundRoute = AuthenticatedOutboundRouteImport.update({
  id: '/outbound',
  path: '/outbound',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedForgeRoute = AuthenticatedForgeRouteImport.update({
  id: '/forge',
  path: '/forge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoworkRoute = AuthenticatedCoworkRouteImport.update({
  id: '/cowork',
  path: '/cowork',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBudgetRoute = AuthenticatedBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutomateRoute = AuthenticatedAutomateRouteImport.update({
  id: '/automate',
  path: '/automate',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgentsModelsRoute =
  AuthenticatedAgentsModelsRouteImport.update({
    id: '/agents-models',
    path: '/agents-models',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBudgetIndexRoute =
  AuthenticatedBudgetIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedBudgetRoute,
  } as any)
const ApiPublicGenerateLinkedinImageRoute =
  ApiPublicGenerateLinkedinImageRouteImport.update({
    id: '/api/public/generate-linkedin-image',
    path: '/api/public/generate-linkedin-image',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSettingsModelsRoute =
  AuthenticatedSettingsModelsRouteImport.update({
    id: '/settings/models',
    path: '/settings/models',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsConnectionsRoute =
  AuthenticatedSettingsConnectionsRouteImport.update({
    id: '/settings/connections',
    path: '/settings/connections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOutboundArchiveRoute =
  AuthenticatedOutboundArchiveRouteImport.update({
    id: '/archive',
    path: '/archive',
    getParentRoute: () => AuthenticatedOutboundRoute,
  } as any)
const AuthenticatedBudgetStatementsRoute =
  AuthenticatedBudgetStatementsRouteImport.update({
    id: '/statements',
    path: '/statements',
    getParentRoute: () => AuthenticatedBudgetRoute,
  } as any)
const AuthenticatedBudgetSensitivityRoute =
  AuthenticatedBudgetSensitivityRouteImport.update({
    id: '/sensitivity',
    path: '/sensitivity',
    getParentRoute: () => AuthenticatedBudgetRoute,
  } as any)
const AuthenticatedBudgetScenariosRoute =
  AuthenticatedBudgetScenariosRouteImport.update({
    id: '/scenarios',
    path: '/scenarios',
    getParentRoute: () => AuthenticatedBudgetRoute,
  } as any)
const AuthenticatedBudgetResultsRoute =
  AuthenticatedBudgetResultsRouteImport.update({
    id: '/results',
    path: '/results',
    getParentRoute: () => AuthenticatedBudgetRoute,
  } as any)
const AuthenticatedBudgetMonthlyRoute =
  AuthenticatedBudgetMonthlyRouteImport.update({
    id: '/monthly',
    path: '/monthly',
    getParentRoute: () => AuthenticatedBudgetRoute,
  } as any)
const AuthenticatedBudgetFinancingRoute =
  AuthenticatedBudgetFinancingRouteImport.update({
    id: '/financing',
    path: '/financing',
    getParentRoute: () => AuthenticatedBudgetRoute,
  } as any)
const AuthenticatedBudgetCompareRoute =
  AuthenticatedBudgetCompareRouteImport.update({
    id: '/compare',
    path: '/compare',
    getParentRoute: () => AuthenticatedBudgetRoute,
  } as any)
const AuthenticatedBudgetChangelogRoute =
  AuthenticatedBudgetChangelogRouteImport.update({
    id: '/changelog',
    path: '/changelog',
    getParentRoute: () => AuthenticatedBudgetRoute,
  } as any)
const AuthenticatedBudgetBoardRoute =
  AuthenticatedBudgetBoardRouteImport.update({
    id: '/board',
    path: '/board',
    getParentRoute: () => AuthenticatedBudgetRoute,
  } as any)
const AuthenticatedBudgetAssumptionsRoute =
  AuthenticatedBudgetAssumptionsRouteImport.update({
    id: '/assumptions',
    path: '/assumptions',
    getParentRoute: () => AuthenticatedBudgetRoute,
  } as any)
const ApiPublicCronWeeklyDraftsRoute =
  ApiPublicCronWeeklyDraftsRouteImport.update({
    id: '/api/public/cron/weekly-drafts',
    path: '/api/public/cron/weekly-drafts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronScheduledOutboundRoute =
  ApiPublicCronScheduledOutboundRouteImport.update({
    id: '/api/public/cron/scheduled-outbound',
    path: '/api/public/cron/scheduled-outbound',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronScheduleTickRoute =
  ApiPublicCronScheduleTickRouteImport.update({
    id: '/api/public/cron/schedule-tick',
    path: '/api/public/cron/schedule-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronMondayBoardRoute =
  ApiPublicCronMondayBoardRouteImport.update({
    id: '/api/public/cron/monday-board',
    path: '/api/public/cron/monday-board',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronLeadReplyTriageRoute =
  ApiPublicCronLeadReplyTriageRouteImport.update({
    id: '/api/public/cron/lead-reply-triage',
    path: '/api/public/cron/lead-reply-triage',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronJobTickRoute = ApiPublicCronJobTickRouteImport.update({
  id: '/api/public/cron/job-tick',
  path: '/api/public/cron/job-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronDailyReportsRoute =
  ApiPublicCronDailyReportsRouteImport.update({
    id: '/api/public/cron/daily-reports',
    path: '/api/public/cron/daily-reports',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronDailyReminderRoute =
  ApiPublicCronDailyReminderRouteImport.update({
    id: '/api/public/cron/daily-reminder',
    path: '/api/public/cron/daily-reminder',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronApprovalSweeperRoute =
  ApiPublicCronApprovalSweeperRouteImport.update({
    id: '/api/public/cron/approval-sweeper',
    path: '/api/public/cron/approval-sweeper',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/agents-models': typeof AuthenticatedAgentsModelsRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/automate': typeof AuthenticatedAutomateRoute
  '/budget': typeof AuthenticatedBudgetRouteWithChildren
  '/chat': typeof AuthenticatedChatRoute
  '/cowork': typeof AuthenticatedCoworkRoute
  '/forge': typeof AuthenticatedForgeRoute
  '/outbound': typeof AuthenticatedOutboundRouteWithChildren
  '/terminal': typeof AuthenticatedTerminalRoute
  '/budget/assumptions': typeof AuthenticatedBudgetAssumptionsRoute
  '/budget/board': typeof AuthenticatedBudgetBoardRoute
  '/budget/changelog': typeof AuthenticatedBudgetChangelogRoute
  '/budget/compare': typeof AuthenticatedBudgetCompareRoute
  '/budget/financing': typeof AuthenticatedBudgetFinancingRoute
  '/budget/monthly': typeof AuthenticatedBudgetMonthlyRoute
  '/budget/results': typeof AuthenticatedBudgetResultsRoute
  '/budget/scenarios': typeof AuthenticatedBudgetScenariosRoute
  '/budget/sensitivity': typeof AuthenticatedBudgetSensitivityRoute
  '/budget/statements': typeof AuthenticatedBudgetStatementsRoute
  '/outbound/archive': typeof AuthenticatedOutboundArchiveRoute
  '/settings/connections': typeof AuthenticatedSettingsConnectionsRoute
  '/settings/models': typeof AuthenticatedSettingsModelsRoute
  '/api/public/generate-linkedin-image': typeof ApiPublicGenerateLinkedinImageRoute
  '/budget/': typeof AuthenticatedBudgetIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/api/public/cron/approval-sweeper': typeof ApiPublicCronApprovalSweeperRoute
  '/api/public/cron/daily-reminder': typeof ApiPublicCronDailyReminderRoute
  '/api/public/cron/daily-reports': typeof ApiPublicCronDailyReportsRoute
  '/api/public/cron/job-tick': typeof ApiPublicCronJobTickRoute
  '/api/public/cron/lead-reply-triage': typeof ApiPublicCronLeadReplyTriageRoute
  '/api/public/cron/monday-board': typeof ApiPublicCronMondayBoardRoute
  '/api/public/cron/schedule-tick': typeof ApiPublicCronScheduleTickRoute
  '/api/public/cron/scheduled-outbound': typeof ApiPublicCronScheduledOutboundRoute
  '/api/public/cron/weekly-drafts': typeof ApiPublicCronWeeklyDraftsRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/agents-models': typeof AuthenticatedAgentsModelsRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/automate': typeof AuthenticatedAutomateRoute
  '/chat': typeof AuthenticatedChatRoute
  '/cowork': typeof AuthenticatedCoworkRoute
  '/forge': typeof AuthenticatedForgeRoute
  '/outbound': typeof AuthenticatedOutboundRouteWithChildren
  '/terminal': typeof AuthenticatedTerminalRoute
  '/': typeof AuthenticatedIndexRoute
  '/budget/assumptions': typeof AuthenticatedBudgetAssumptionsRoute
  '/budget/board': typeof AuthenticatedBudgetBoardRoute
  '/budget/changelog': typeof AuthenticatedBudgetChangelogRoute
  '/budget/compare': typeof AuthenticatedBudgetCompareRoute
  '/budget/financing': typeof AuthenticatedBudgetFinancingRoute
  '/budget/monthly': typeof AuthenticatedBudgetMonthlyRoute
  '/budget/results': typeof AuthenticatedBudgetResultsRoute
  '/budget/scenarios': typeof AuthenticatedBudgetScenariosRoute
  '/budget/sensitivity': typeof AuthenticatedBudgetSensitivityRoute
  '/budget/statements': typeof AuthenticatedBudgetStatementsRoute
  '/outbound/archive': typeof AuthenticatedOutboundArchiveRoute
  '/settings/connections': typeof AuthenticatedSettingsConnectionsRoute
  '/settings/models': typeof AuthenticatedSettingsModelsRoute
  '/api/public/generate-linkedin-image': typeof ApiPublicGenerateLinkedinImageRoute
  '/budget': typeof AuthenticatedBudgetIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/api/public/cron/approval-sweeper': typeof ApiPublicCronApprovalSweeperRoute
  '/api/public/cron/daily-reminder': typeof ApiPublicCronDailyReminderRoute
  '/api/public/cron/daily-reports': typeof ApiPublicCronDailyReportsRoute
  '/api/public/cron/job-tick': typeof ApiPublicCronJobTickRoute
  '/api/public/cron/lead-reply-triage': typeof ApiPublicCronLeadReplyTriageRoute
  '/api/public/cron/monday-board': typeof ApiPublicCronMondayBoardRoute
  '/api/public/cron/schedule-tick': typeof ApiPublicCronScheduleTickRoute
  '/api/public/cron/scheduled-outbound': typeof ApiPublicCronScheduledOutboundRoute
  '/api/public/cron/weekly-drafts': typeof ApiPublicCronWeeklyDraftsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/agents-models': typeof AuthenticatedAgentsModelsRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/automate': typeof AuthenticatedAutomateRoute
  '/_authenticated/budget': typeof AuthenticatedBudgetRouteWithChildren
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/cowork': typeof AuthenticatedCoworkRoute
  '/_authenticated/forge': typeof AuthenticatedForgeRoute
  '/_authenticated/outbound': typeof AuthenticatedOutboundRouteWithChildren
  '/_authenticated/terminal': typeof AuthenticatedTerminalRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/budget/assumptions': typeof AuthenticatedBudgetAssumptionsRoute
  '/_authenticated/budget/board': typeof AuthenticatedBudgetBoardRoute
  '/_authenticated/budget/changelog': typeof AuthenticatedBudgetChangelogRoute
  '/_authenticated/budget/compare': typeof AuthenticatedBudgetCompareRoute
  '/_authenticated/budget/financing': typeof AuthenticatedBudgetFinancingRoute
  '/_authenticated/budget/monthly': typeof AuthenticatedBudgetMonthlyRoute
  '/_authenticated/budget/results': typeof AuthenticatedBudgetResultsRoute
  '/_authenticated/budget/scenarios': typeof AuthenticatedBudgetScenariosRoute
  '/_authenticated/budget/sensitivity': typeof AuthenticatedBudgetSensitivityRoute
  '/_authenticated/budget/statements': typeof AuthenticatedBudgetStatementsRoute
  '/_authenticated/outbound/archive': typeof AuthenticatedOutboundArchiveRoute
  '/_authenticated/settings/connections': typeof AuthenticatedSettingsConnectionsRoute
  '/_authenticated/settings/models': typeof AuthenticatedSettingsModelsRoute
  '/api/public/generate-linkedin-image': typeof ApiPublicGenerateLinkedinImageRoute
  '/_authenticated/budget/': typeof AuthenticatedBudgetIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/api/public/cron/approval-sweeper': typeof ApiPublicCronApprovalSweeperRoute
  '/api/public/cron/daily-reminder': typeof ApiPublicCronDailyReminderRoute
  '/api/public/cron/daily-reports': typeof ApiPublicCronDailyReportsRoute
  '/api/public/cron/job-tick': typeof ApiPublicCronJobTickRoute
  '/api/public/cron/lead-reply-triage': typeof ApiPublicCronLeadReplyTriageRoute
  '/api/public/cron/monday-board': typeof ApiPublicCronMondayBoardRoute
  '/api/public/cron/schedule-tick': typeof ApiPublicCronScheduleTickRoute
  '/api/public/cron/scheduled-outbound': typeof ApiPublicCronScheduledOutboundRoute
  '/api/public/cron/weekly-drafts': typeof ApiPublicCronWeeklyDraftsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/agents-models'
    | '/approvals'
    | '/automate'
    | '/budget'
    | '/chat'
    | '/cowork'
    | '/forge'
    | '/outbound'
    | '/terminal'
    | '/budget/assumptions'
    | '/budget/board'
    | '/budget/changelog'
    | '/budget/compare'
    | '/budget/financing'
    | '/budget/monthly'
    | '/budget/results'
    | '/budget/scenarios'
    | '/budget/sensitivity'
    | '/budget/statements'
    | '/outbound/archive'
    | '/settings/connections'
    | '/settings/models'
    | '/api/public/generate-linkedin-image'
    | '/budget/'
    | '/settings/'
    | '/api/public/cron/approval-sweeper'
    | '/api/public/cron/daily-reminder'
    | '/api/public/cron/daily-reports'
    | '/api/public/cron/job-tick'
    | '/api/public/cron/lead-reply-triage'
    | '/api/public/cron/monday-board'
    | '/api/public/cron/schedule-tick'
    | '/api/public/cron/scheduled-outbound'
    | '/api/public/cron/weekly-drafts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/agents-models'
    | '/approvals'
    | '/automate'
    | '/chat'
    | '/cowork'
    | '/forge'
    | '/outbound'
    | '/terminal'
    | '/'
    | '/budget/assumptions'
    | '/budget/board'
    | '/budget/changelog'
    | '/budget/compare'
    | '/budget/financing'
    | '/budget/monthly'
    | '/budget/results'
    | '/budget/scenarios'
    | '/budget/sensitivity'
    | '/budget/statements'
    | '/outbound/archive'
    | '/settings/connections'
    | '/settings/models'
    | '/api/public/generate-linkedin-image'
    | '/budget'
    | '/settings'
    | '/api/public/cron/approval-sweeper'
    | '/api/public/cron/daily-reminder'
    | '/api/public/cron/daily-reports'
    | '/api/public/cron/job-tick'
    | '/api/public/cron/lead-reply-triage'
    | '/api/public/cron/monday-board'
    | '/api/public/cron/schedule-tick'
    | '/api/public/cron/scheduled-outbound'
    | '/api/public/cron/weekly-drafts'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/agents-models'
    | '/_authenticated/approvals'
    | '/_authenticated/automate'
    | '/_authenticated/budget'
    | '/_authenticated/chat'
    | '/_authenticated/cowork'
    | '/_authenticated/forge'
    | '/_authenticated/outbound'
    | '/_authenticated/terminal'
    | '/_authenticated/'
    | '/_authenticated/budget/assumptions'
    | '/_authenticated/budget/board'
    | '/_authenticated/budget/changelog'
    | '/_authenticated/budget/compare'
    | '/_authenticated/budget/financing'
    | '/_authenticated/budget/monthly'
    | '/_authenticated/budget/results'
    | '/_authenticated/budget/scenarios'
    | '/_authenticated/budget/sensitivity'
    | '/_authenticated/budget/statements'
    | '/_authenticated/outbound/archive'
    | '/_authenticated/settings/connections'
    | '/_authenticated/settings/models'
    | '/api/public/generate-linkedin-image'
    | '/_authenticated/budget/'
    | '/_authenticated/settings/'
    | '/api/public/cron/approval-sweeper'
    | '/api/public/cron/daily-reminder'
    | '/api/public/cron/daily-reports'
    | '/api/public/cron/job-tick'
    | '/api/public/cron/lead-reply-triage'
    | '/api/public/cron/monday-board'
    | '/api/public/cron/schedule-tick'
    | '/api/public/cron/scheduled-outbound'
    | '/api/public/cron/weekly-drafts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicGenerateLinkedinImageRoute: typeof ApiPublicGenerateLinkedinImageRoute
  ApiPublicCronApprovalSweeperRoute: typeof ApiPublicCronApprovalSweeperRoute
  ApiPublicCronDailyReminderRoute: typeof ApiPublicCronDailyReminderRoute
  ApiPublicCronDailyReportsRoute: typeof ApiPublicCronDailyReportsRoute
  ApiPublicCronJobTickRoute: typeof ApiPublicCronJobTickRoute
  ApiPublicCronLeadReplyTriageRoute: typeof ApiPublicCronLeadReplyTriageRoute
  ApiPublicCronMondayBoardRoute: typeof ApiPublicCronMondayBoardRoute
  ApiPublicCronScheduleTickRoute: typeof ApiPublicCronScheduleTickRoute
  ApiPublicCronScheduledOutboundRoute: typeof ApiPublicCronScheduledOutboundRoute
  ApiPublicCronWeeklyDraftsRoute: typeof ApiPublicCronWeeklyDraftsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/terminal': {
      id: '/_authenticated/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof AuthenticatedTerminalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/outbound': {
      id: '/_authenticated/outbound'
      path: '/outbound'
      fullPath: '/outbound'
      preLoaderRoute: typeof AuthenticatedOutboundRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forge': {
      id: '/_authenticated/forge'
      path: '/forge'
      fullPath: '/forge'
      preLoaderRoute: typeof AuthenticatedForgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cowork': {
      id: '/_authenticated/cowork'
      path: '/cowork'
      fullPath: '/cowork'
      preLoaderRoute: typeof AuthenticatedCoworkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/budget': {
      id: '/_authenticated/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof AuthenticatedBudgetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automate': {
      id: '/_authenticated/automate'
      path: '/automate'
      fullPath: '/automate'
      preLoaderRoute: typeof AuthenticatedAutomateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agents-models': {
      id: '/_authenticated/agents-models'
      path: '/agents-models'
      fullPath: '/agents-models'
      preLoaderRoute: typeof AuthenticatedAgentsModelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/budget/': {
      id: '/_authenticated/budget/'
      path: '/'
      fullPath: '/budget/'
      preLoaderRoute: typeof AuthenticatedBudgetIndexRouteImport
      parentRoute: typeof AuthenticatedBudgetRoute
    }
    '/api/public/generate-linkedin-image': {
      id: '/api/public/generate-linkedin-image'
      path: '/api/public/generate-linkedin-image'
      fullPath: '/api/public/generate-linkedin-image'
      preLoaderRoute: typeof ApiPublicGenerateLinkedinImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/models': {
      id: '/_authenticated/settings/models'
      path: '/settings/models'
      fullPath: '/settings/models'
      preLoaderRoute: typeof AuthenticatedSettingsModelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/connections': {
      id: '/_authenticated/settings/connections'
      path: '/settings/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof AuthenticatedSettingsConnectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/outbound/archive': {
      id: '/_authenticated/outbound/archive'
      path: '/archive'
      fullPath: '/outbound/archive'
      preLoaderRoute: typeof AuthenticatedOutboundArchiveRouteImport
      parentRoute: typeof AuthenticatedOutboundRoute
    }
    '/_authenticated/budget/statements': {
      id: '/_authenticated/budget/statements'
      path: '/statements'
      fullPath: '/budget/statements'
      preLoaderRoute: typeof AuthenticatedBudgetStatementsRouteImport
      parentRoute: typeof AuthenticatedBudgetRoute
    }
    '/_authenticated/budget/sensitivity': {
      id: '/_authenticated/budget/sensitivity'
      path: '/sensitivity'
      fullPath: '/budget/sensitivity'
      preLoaderRoute: typeof AuthenticatedBudgetSensitivityRouteImport
      parentRoute: typeof AuthenticatedBudgetRoute
    }
    '/_authenticated/budget/scenarios': {
      id: '/_authenticated/budget/scenarios'
      path: '/scenarios'
      fullPath: '/budget/scenarios'
      preLoaderRoute: typeof AuthenticatedBudgetScenariosRouteImport
      parentRoute: typeof AuthenticatedBudgetRoute
    }
    '/_authenticated/budget/results': {
      id: '/_authenticated/budget/results'
      path: '/results'
      fullPath: '/budget/results'
      preLoaderRoute: typeof AuthenticatedBudgetResultsRouteImport
      parentRoute: typeof AuthenticatedBudgetRoute
    }
    '/_authenticated/budget/monthly': {
      id: '/_authenticated/budget/monthly'
      path: '/monthly'
      fullPath: '/budget/monthly'
      preLoaderRoute: typeof AuthenticatedBudgetMonthlyRouteImport
      parentRoute: typeof AuthenticatedBudgetRoute
    }
    '/_authenticated/budget/financing': {
      id: '/_authenticated/budget/financing'
      path: '/financing'
      fullPath: '/budget/financing'
      preLoaderRoute: typeof AuthenticatedBudgetFinancingRouteImport
      parentRoute: typeof AuthenticatedBudgetRoute
    }
    '/_authenticated/budget/compare': {
      id: '/_authenticated/budget/compare'
      path: '/compare'
      fullPath: '/budget/compare'
      preLoaderRoute: typeof AuthenticatedBudgetCompareRouteImport
      parentRoute: typeof AuthenticatedBudgetRoute
    }
    '/_authenticated/budget/changelog': {
      id: '/_authenticated/budget/changelog'
      path: '/changelog'
      fullPath: '/budget/changelog'
      preLoaderRoute: typeof AuthenticatedBudgetChangelogRouteImport
      parentRoute: typeof AuthenticatedBudgetRoute
    }
    '/_authenticated/budget/board': {
      id: '/_authenticated/budget/board'
      path: '/board'
      fullPath: '/budget/board'
      preLoaderRoute: typeof AuthenticatedBudgetBoardRouteImport
      parentRoute: typeof AuthenticatedBudgetRoute
    }
    '/_authenticated/budget/assumptions': {
      id: '/_authenticated/budget/assumptions'
      path: '/assumptions'
      fullPath: '/budget/assumptions'
      preLoaderRoute: typeof AuthenticatedBudgetAssumptionsRouteImport
      parentRoute: typeof AuthenticatedBudgetRoute
    }
    '/api/public/cron/weekly-drafts': {
      id: '/api/public/cron/weekly-drafts'
      path: '/api/public/cron/weekly-drafts'
      fullPath: '/api/public/cron/weekly-drafts'
      preLoaderRoute: typeof ApiPublicCronWeeklyDraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/scheduled-outbound': {
      id: '/api/public/cron/scheduled-outbound'
      path: '/api/public/cron/scheduled-outbound'
      fullPath: '/api/public/cron/scheduled-outbound'
      preLoaderRoute: typeof ApiPublicCronScheduledOutboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/schedule-tick': {
      id: '/api/public/cron/schedule-tick'
      path: '/api/public/cron/schedule-tick'
      fullPath: '/api/public/cron/schedule-tick'
      preLoaderRoute: typeof ApiPublicCronScheduleTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/monday-board': {
      id: '/api/public/cron/monday-board'
      path: '/api/public/cron/monday-board'
      fullPath: '/api/public/cron/monday-board'
      preLoaderRoute: typeof ApiPublicCronMondayBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/lead-reply-triage': {
      id: '/api/public/cron/lead-reply-triage'
      path: '/api/public/cron/lead-reply-triage'
      fullPath: '/api/public/cron/lead-reply-triage'
      preLoaderRoute: typeof ApiPublicCronLeadReplyTriageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/job-tick': {
      id: '/api/public/cron/job-tick'
      path: '/api/public/cron/job-tick'
      fullPath: '/api/public/cron/job-tick'
      preLoaderRoute: typeof ApiPublicCronJobTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/daily-reports': {
      id: '/api/public/cron/daily-reports'
      path: '/api/public/cron/daily-reports'
      fullPath: '/api/public/cron/daily-reports'
      preLoaderRoute: typeof ApiPublicCronDailyReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/daily-reminder': {
      id: '/api/public/cron/daily-reminder'
      path: '/api/public/cron/daily-reminder'
      fullPath: '/api/public/cron/daily-reminder'
      preLoaderRoute: typeof ApiPublicCronDailyReminderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/approval-sweeper': {
      id: '/api/public/cron/approval-sweeper'
      path: '/api/public/cron/approval-sweeper'
      fullPath: '/api/public/cron/approval-sweeper'
      preLoaderRoute: typeof ApiPublicCronApprovalSweeperRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedBudgetRouteChildren {
  AuthenticatedBudgetAssumptionsRoute: typeof AuthenticatedBudgetAssumptionsRoute
  AuthenticatedBudgetBoardRoute: typeof AuthenticatedBudgetBoardRoute
  AuthenticatedBudgetChangelogRoute: typeof AuthenticatedBudgetChangelogRoute
  AuthenticatedBudgetCompareRoute: typeof AuthenticatedBudgetCompareRoute
  AuthenticatedBudgetFinancingRoute: typeof AuthenticatedBudgetFinancingRoute
  AuthenticatedBudgetMonthlyRoute: typeof AuthenticatedBudgetMonthlyRoute
  AuthenticatedBudgetResultsRoute: typeof AuthenticatedBudgetResultsRoute
  AuthenticatedBudgetScenariosRoute: typeof AuthenticatedBudgetScenariosRoute
  AuthenticatedBudgetSensitivityRoute: typeof AuthenticatedBudgetSensitivityRoute
  AuthenticatedBudgetStatementsRoute: typeof AuthenticatedBudgetStatementsRoute
  AuthenticatedBudgetIndexRoute: typeof AuthenticatedBudgetIndexRoute
}

const AuthenticatedBudgetRouteChildren: AuthenticatedBudgetRouteChildren = {
  AuthenticatedBudgetAssumptionsRoute: AuthenticatedBudgetAssumptionsRoute,
  AuthenticatedBudgetBoardRoute: AuthenticatedBudgetBoardRoute,
  AuthenticatedBudgetChangelogRoute: AuthenticatedBudgetChangelogRoute,
  AuthenticatedBudgetCompareRoute: AuthenticatedBudgetCompareRoute,
  AuthenticatedBudgetFinancingRoute: AuthenticatedBudgetFinancingRoute,
  AuthenticatedBudgetMonthlyRoute: AuthenticatedBudgetMonthlyRoute,
  AuthenticatedBudgetResultsRoute: AuthenticatedBudgetResultsRoute,
  AuthenticatedBudgetScenariosRoute: AuthenticatedBudgetScenariosRoute,
  AuthenticatedBudgetSensitivityRoute: AuthenticatedBudgetSensitivityRoute,
  AuthenticatedBudgetStatementsRoute: AuthenticatedBudgetStatementsRoute,
  AuthenticatedBudgetIndexRoute: AuthenticatedBudgetIndexRoute,
}

const AuthenticatedBudgetRouteWithChildren =
  AuthenticatedBudgetRoute._addFileChildren(AuthenticatedBudgetRouteChildren)

interface AuthenticatedOutboundRouteChildren {
  AuthenticatedOutboundArchiveRoute: typeof AuthenticatedOutboundArchiveRoute
}

const AuthenticatedOutboundRouteChildren: AuthenticatedOutboundRouteChildren = {
  AuthenticatedOutboundArchiveRoute: AuthenticatedOutboundArchiveRoute,
}

const AuthenticatedOutboundRouteWithChildren =
  AuthenticatedOutboundRoute._addFileChildren(
    AuthenticatedOutboundRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgentsModelsRoute: typeof AuthenticatedAgentsModelsRoute
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedAutomateRoute: typeof AuthenticatedAutomateRoute
  AuthenticatedBudgetRoute: typeof AuthenticatedBudgetRouteWithChildren
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedCoworkRoute: typeof AuthenticatedCoworkRoute
  AuthenticatedForgeRoute: typeof AuthenticatedForgeRoute
  AuthenticatedOutboundRoute: typeof AuthenticatedOutboundRouteWithChildren
  AuthenticatedTerminalRoute: typeof AuthenticatedTerminalRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedSettingsConnectionsRoute: typeof AuthenticatedSettingsConnectionsRoute
  AuthenticatedSettingsModelsRoute: typeof AuthenticatedSettingsModelsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgentsModelsRoute: AuthenticatedAgentsModelsRoute,
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedAutomateRoute: AuthenticatedAutomateRoute,
  AuthenticatedBudgetRoute: AuthenticatedBudgetRouteWithChildren,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedCoworkRoute: AuthenticatedCoworkRoute,
  AuthenticatedForgeRoute: AuthenticatedForgeRoute,
  AuthenticatedOutboundRoute: AuthenticatedOutboundRouteWithChildren,
  AuthenticatedTerminalRoute: AuthenticatedTerminalRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedSettingsConnectionsRoute: AuthenticatedSettingsConnectionsRoute,
  AuthenticatedSettingsModelsRoute: AuthenticatedSettingsModelsRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicGenerateLinkedinImageRoute: ApiPublicGenerateLinkedinImageRoute,
  ApiPublicCronApprovalSweeperRoute: ApiPublicCronApprovalSweeperRoute,
  ApiPublicCronDailyReminderRoute: ApiPublicCronDailyReminderRoute,
  ApiPublicCronDailyReportsRoute: ApiPublicCronDailyReportsRoute,
  ApiPublicCronJobTickRoute: ApiPublicCronJobTickRoute,
  ApiPublicCronLeadReplyTriageRoute: ApiPublicCronLeadReplyTriageRoute,
  ApiPublicCronMondayBoardRoute: ApiPublicCronMondayBoardRoute,
  ApiPublicCronScheduleTickRoute: ApiPublicCronScheduleTickRoute,
  ApiPublicCronScheduledOutboundRoute: ApiPublicCronScheduledOutboundRoute,
  ApiPublicCronWeeklyDraftsRoute: ApiPublicCronWeeklyDraftsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
